<?php

class FSS_Report_Generate {

	var $fielddata;
	var $filterdata;
	var $extradata;
	var $options;

	static function processAlias($alias)
	{
		$target_folder = JPATH_SITE.DS.'components'.DS.'com_fss'.DS.'plugins'.DS.'reports'.DS.'custom'.DS;

		$count = 1;
		$target_file = $alias;

		while (file_exists($target_folder . $target_file . ".xml"))
		{
			$content = file_get_contents($target_folder . $target_file . ".xml");
			if (strpos($content, 'GENERATED BY REPORT_BUILDER') !== FALSE)
				break;
			$count++;
			$target_file = $alias."-".$count;
		}

		return $target_file;		
	}

	static function makeReportObject($reportid)
	{
		$db = JFactory::getDBO();
		$sql = "SELECT * FROM #__fsj_fssadd_report WHERE id = $reportid";
		$db->setQuery($sql);
		$report = $db->loadObject();

		$type = $report->type;
		$class = "FSS_Report_Generate_" . $type;
		$file = JPATH_SITE.DS.'administrator'.DS.'components'.DS.'com_fsj_fssadd'.DS.'helpers'.DS.'reports'.DS.$type.".php";

		if (!file_exists($file))
		{
			$class = "FSS_Report_Generate_ticketlist";
			$file = JPATH_SITE.DS.'administrator'.DS.'components'.DS.'com_fsj_fssadd'.DS.'helpers'.DS.'reports'.DS."ticketlist.php";
		}

		require_once($file);

		return new $class($report);
	}

	function __construct($report)
	{
		$this->report = $report;

		$this->fielddata = json_decode($report->fielddata);
		$this->filterdata = json_decode($report->filterdata);
		$this->extradata = json_decode($report->extradata);
		$this->options = json_decode($report->options);

		if ($this->report->type == "") $this->report->type = "ticketlist";
	}


	function publishReport()
	{
		$target_file = JPATH_SITE.DS.'components'.DS.'com_fss'.DS.'plugins'.DS.'reports'.DS.'custom'.DS.$this->report->alias.".xml";
		$xml = array();
		$xml[] = '<?xml version="1.0" encoding="utf-8" ?>';
		$xml[] = '<report>';
		$xml[] = '<!-- GENERATED BY REPORT_BUILDER -->';
		$xml[] = $this->generateReport();
		$xml[] = '</report>';

		file_put_contents($target_file, implode("\n", $xml));
	}

	function removeReport()
	{
		$target_file = JPATH_SITE.DS.'components'.DS.'com_fss'.DS.'plugins'.DS.'reports'.DS.'custom'.DS.$this->report->alias.".xml";
		if (file_exists($target_file)) unlink($target_file);
	}

	function includeTemplate()
	{
		$tmpl = JPATH_SITE.DS.'administrator'.DS.'components'.DS.'com_fsj_fssadd'.DS.'helpers'.DS.'reports'.DS.$this->report->type.DS.$this->report->type.".tmpl.php";
		if (file_exists($tmpl))
		{
			ob_clean();
			include($tmpl);
			return ob_get_clean();
		} else {
			return "Template missing!";
		}
	}

	function makeField($label, $attribs)
	{
		$attr = array();
		foreach ($attribs as $key => $value)
			$attr[] = " $key=\"" . htmlspecialchars($value) . "\" ";

		return "<field " . implode($attr) . ">" . htmlentities($label) . "</field>";
	}

	/**
	 * A report builder should override all the functions below to implement its xml and ui
	 */

	function generateReport()
	{
		$template = $this->includeTemplate();
		return $template;
	}


	function getFields()
	{

	}

	function getFilters()
	{

	} 

	function getExtras()
	{

	}

	function getOptions()
	{

	}
}